name: scpo-bootcamp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # colab 2023: 3.10.12 (2022: 3.7.13)
  - pip=23.1.2  # colab 2023
  - jupyterlab
  - scipy=1.10.1  # (2022: 1.4.1)
  - numpy=1.23.5  # (2022: 1.21.6)
  - pandas=1.5.3  # (2022: 1.3.5)
  - matplotlib=3.7.1  # (2022: 3.2.2)
  - seaborn=0.12.2  # (2022: 0.11.2)
  - scikit-learn=1.2.2  # (2022: 1.0.2)
